name: Percy Visual Tests with Figma

on: [pull_request]

jobs:
  visual-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Start app in background
        run: |
          npm run start &
          sleep 5 # espera que arranque

      - name: Run Percy visual tests
        run: npx percy exec -- npx playwright test
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}